# Imports
```{r library}
if(!require('factoextra')) {
  install.packages('factoextra')
  library('factoextra')
}
if(!require('NbClust')) {
  install.packages('NbClust')
  library('NbClust')
}
if(!require('xtable')) {
  install.packages('xtable')
  library('xtable')
}

if(!require('dtwclust')) {
  install.packages('dtwclust')
  library('dtwclust')
}
if(!require('parallel')) {
  install.packages('parallel')
  library('parallel')
}

if(!require('doParallel')) {
  install.packages('doParallel')
}

if(!require('plot3D')) {
  install.packages('plot3D')
  library('plot3D')
}


if(!require('viridis')){
    install.packages("viridis")
    library(viridis)
}

```
```{r src}
source("./R/synthetic_data.R")
```
# Mixed
## Get data


```{r get data}
n <- 500
y <- get_cluster_labels(n)
y.dyn <- get_dynamic_cluster_labels(n)

set.seed(776)
X <- get_static_points(n)
X$x3 <- y.dyn

```

## Preprocessing
```{r normalize and plot}
png(filename="./output/plots/2_mixed_static_data.png")
scatter3D(X$x1, X$x2, X$x3, colvar=y, col=viridis(4), colkey=FALSE)
dev.off()
```
## Clustering parameter tuning
```{r check Silhouette and Elbow method}
png(filename="./output/plots/2_mixed_static_data.elbow1.png")
fviz_nbclust(X, hcut, method = "wss", k.max=10,
               hc_func = "hclust",
  hc_method = "ward.D2",
  hc_metric = "euclidean") +
  labs(subtitle = "Elbow method")
dev.off()

png(filename="./output/plots/2_mixed_static_data.elbow2.png")
fviz_nbclust(X, hcut, method = "silhouette", k.max=10,
               hc_func = "hclust",
  hc_method = "ward.D2",
  hc_metric = "euclidean")+
  labs(subtitle = "Silhouette method")
dev.off()
```
# Get clusters
```{r get clusters}
k = 4
X.static.clust <- hcut(X, k = k, stand = FALSE, hc_func = "hclust",
  hc_method = "ward.D2",
  hc_metric = "euclidean")
fviz_silhouette(X.static.clust)
fviz_cluster(X.static.clust, geom="point")
```

```{r get clusters and plot}
scatter3D(X$x1, X$x2, X$x3, colvar=X.static.clust$cluster)
```