```{r}
# Parse char -> date
if(!require('dplyr')) {
  install.packages('dplyr')
  library('dplyr')
}
if(!require('lubridate')) {
  install.packages('lubridate')
  library('lubridate')
}

if(!require('ggplot2')) {
  install.packages('ggplot2')
  library('ggplot2')
}
```
```{r src}
k.dyn.D <- 4
k.stat.D <- 4
N.D <- 500
T.D <- 500
d.D <- 8
```

# Template
No difference between the two
```{r src}
ggplot(read.csv("./output/benchmark_20250418_155854.csv") %>%
distinct(method, k.dyn, k.stat, N, T, d, .keep_all = TRUE) %>%
filter(k.dyn==k.dyn.D & k.stat==k.stat.D & N == N.D & T == T.D & d == d.D) %>% 
as.data.frame(), 
    aes(x=k.dyn, y=seconds, group=method, color=method)) + 
    geom_line(size=2)
```

# Number of dynamic clusters 
No difference between the two
```{r src}
ggplot(read.csv("./output/benchmark_20250418_155854.csv") %>%
distinct(method, k.dyn, k.stat, N, T, d, .keep_all = TRUE) %>%
filter(k.stat==k.stat.D & N == N.D & T == T.D & d == d.D) %>% 
as.data.frame(), 
    aes(x=k.dyn, y=seconds, group=method, color=method)) + 
    geom_line(size=2)
```


# Number of static clusters
No difference between the two
```{r src}
ggplot(read.csv("./output/benchmark_20250418_155854.csv") %>%
distinct(method, k.dyn, k.stat, N, T, d, .keep_all = TRUE) %>%
filter(k.dyn==k.dyn.D & N == N.D & T == T.D & d == d.D) %>% 
as.data.frame(), 
    aes(x=k.stat, y=seconds, group=method, color=method)) + 
    geom_line(size=2)
```
# Number of points
No difference between the two
```{r src}
ggplot(read.csv("./output/benchmark_20250418_155854.csv") %>%
distinct(method, k.dyn, k.stat, N, T, d, .keep_all = TRUE) %>%
filter(k.dyn==k.dyn.D & k.stat==k.stat.D & T == T.D & d == d.D) %>% 
as.data.frame(), 
    aes(x=N, y=seconds, group=method, color=method)) + 
    geom_line(size=2)
```
# Number of time series points
No difference between the two
```{r src}
ggplot(read.csv("./output/benchmark_20250418_155854.csv") %>%
distinct(method, k.dyn, k.stat, N, T, d, .keep_all = TRUE) %>%
filter(k.dyn==k.dyn.D & k.stat==k.stat.D & N == N.D & d == d.D) %>% 
as.data.frame(), 
    aes(x=T, y=seconds, group=method, color=method)) + 
    geom_line(size=2)
```
# Number of static variables
No difference between the two
```{r src}
ggplot(read.csv("./output/benchmark_20250418_155854.csv") %>%
distinct(method, k.dyn, k.stat, N, T, d, .keep_all = TRUE) %>%
filter(k.dyn==k.dyn.D & k.stat==k.stat.D & N == N.D & T == T.D) %>% 
as.data.frame(), 
    aes(x=d, y=seconds, group=method, color=method)) + 
    geom_line(size=2)
```